services:
  k8ute:
    image: kpostekk/k8ute:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:alpine

