---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      hostname: operator
      containers:
        - name: operator
          image: kpostekk/k8ute-02:vector
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 22
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: operator
  labels:
    k8ute/expose: "k8ute-k8ute-22"
spec:
  selector:
    app: operator
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: tcp
      port: 9090
      targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source
spec:
  selector:
    matchLabels:
      app: source
  template:
    metadata:
      labels:
        app: source
      annotations:
        k8ute/secret: secret
    spec:
      containers:
        - name: source
          image: kpostekk/k8ute-02:source
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-02-pong
                  key: secret
            - name: TARGET
              value: "operator"
