apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
  labels:
    name: wireguard

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-client
  namespace: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard-client
  template:
    metadata:
      labels:
        app: wireguard-client
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
          - name: net.ipv4.ip_forward
            value: "1"
      containers:
        - name: wireguard
          image: ghcr.io/linuxserver/wireguard
          envFrom:
            - configMapRef:
                name: wireguard-configmap
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          volumeMounts:
            - name: host-volumes
              mountPath: /lib/modules
            - name: wg-cert
              mountPath: /config/wg_confs
          ports:
            - containerPort: 51820
              protocol: UDP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "1"
          livenessProbe:
            exec:
              command: ["/bin/ping", "-q", "-c", "1", "10.13.13.1"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: host-volumes
          hostPath:
            path: /lib/modules
            type: Directory
        - name: wg-cert
          secret:
            secretName: wg-cert
