---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-k8ute-lab
spec:
  selector:
    matchLabels:
      app: kali-k8ute-lab
  template:
    metadata:
      labels:
        app: kali-k8ute-lab
    spec:
      hostname: k8ute-lab
      containers:
      - name: kali-k8ute-lab
        image: kpostekk/k8ute-03:lab
        resources:
          limits:
            memory: "1Gi"
            cpu: "2"
        ports:
        - containerPort: 22

---
apiVersion: v1
kind: Service
metadata:
  name: kali-k8ute-lab
  labels:
    k8ute/expose: "lab"
spec:
  selector:
    app: kali-k8ute-lab
  ports:
  - port: 22
    targetPort: 22

