---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: kpostekk/k8ute-01:wordpress
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.2"
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: secret

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    k8ute/expose: "wordpress"
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: kpostekk/k8ute-01:mariadb
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.2"
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              value: wordpress
            - name: MARIADB_USER
              value: wordpress
            - name: MARIADB_PASSWORD
              value: secret
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: verysecret

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.2"
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    k8ute/expose: "database"
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80
